export const defaultContent = {
  navbar: {
    brandName: "CONNEKTIXX",
    chatCta: "Chat Now",
    navItems: ["Home", "Services", "Clients", "Why Connektixx?", "Reviews", "FAQs", "Contact"],
  },
  home: {
    headline1: "Bridging Connections,",
    headline2: "Driving Success",
    stats: "5+ years | 511+ Brands | 60+ Crore Ad spent",
    subtext: "A dedicated team of specialists, delivering remarkable work to our clients worldwide!",
    cta: "Let's Connect",
    certLabel: "Our Performance Marketing Services are Certified by",
    partners: ["Meta Partner", "Shopify", "Google"],
  },
  services: {
    pill: "Our Services",
    heading: "What We Offer",
    subheading: "Scalable, Smart, and Seamless Solutions",
    body: "At Connektixx, we bring together strategic thinking, creativity, and technology to help you grow faster and connect better. From marketing strategy to digital campaigns to customer engagement, we've got you covered.",
    categories: [
      {
        category: "BPO / Call Centre Services",
        tagline: "Smart, Scalable, Human-Centered Support!",
        description: "At Connektixx, we redefine customer experience by blending empathetic communication with technology-powered operations for effortless scaling.",
        icon: "🎧",
        services: [
          { title: "Inbound Support", description: "Customer support, order management, and technical helpdesk with a human touch.", icon: "🎧" },
          { title: "Outbound Services", description: "Lead generation, telemarketing, customer retention, and market research calls.", icon: "📞" },
          { title: "Omnichannel Support", description: "Live chat, email, and social media messaging across all platforms.", icon: "💬" },
          { title: "Back Office & Data", description: "Data entry, processing, mining, reporting, and catalogue management.", icon: "📊" },
          { title: "Process Automation", description: "AI-enabled workflows, predictive analytics, and real-time dashboards.", icon: "⚙️" },
          { title: "Multichannel CX", description: "Unified customer experience across voice, chat, email, SMS, and social platforms.", icon: "🔄" },
        ],
      },
      {
        category: "Digital Marketing Services",
        tagline: "Data-Driven, Creative, Results-Focused Solutions",
        description: "We combine strategic creativity with technical expertise to drive measurable growth across all digital channels.",
        icon: "🚀",
        services: [
          { title: "SEO", description: "Boost visibility and drive organic growth with technical and content-led SEO.", icon: "🔍" },
          { title: "Performance Marketing", description: "Maximize ROI through Google Ads, Meta Ads, and other paid platforms.", icon: "📈" },
          { title: "Social Media Marketing", description: "Engage your community, grow your following, and build a loyal brand presence.", icon: "📱" },
          { title: "Content Strategy", description: "From blogs to video, we deliver content that educates, entertains, and converts.", icon: "✍️" },
          { title: "CRM Automation", description: "Keep your audience engaged with personalized, automated workflows.", icon: "📧" },
          { title: "Website Development", description: "Create high-converting, visually stunning, and responsive websites.", icon: "💻" },
        ],
      },
      {
        category: "Marketing Consultancy Services",
        tagline: "Strategic Guidance for Sustainable Growth",
        description: "Expert advisory that transforms market insights into actionable strategies for long-term brand success.",
        icon: "💡",
        services: [
          { title: "Brand Strategy", description: "Build a compelling brand identity that stands out and connects with your audience.", icon: "🎯" },
          { title: "Go-to-Market Strategy", description: "Launch your products or services with clarity, confidence, and impact.", icon: "🚀" },
          { title: "Growth Marketing Plans", description: "Data-driven roadmaps customized to your goals, industry, and customer base.", icon: "📊" },
        ],
      },
    ],
  },
  whyChoose: {
    pill: "Our Differentiators",
    heading: "Why Choose Connektixx?",
    subheading: "Your Growth Partners in the Digital Age",
    cta: "Book a Strategy Call",
    services: [
      {
        title: "Why Choose Connektixx for BPO?",
        tagline: "Efficient. Human-Centric. Scalable.",
        features: [
          "24/7 Availability Across Time Zones",
          "Multilingual Capabilities",
          "Trained, Empathetic, and Tech-Savvy Agents",
          "Custom Onboarding & SOP Development",
          "Flexible Pricing Models (FTE, Hourly, Project-Based)",
          "AI + Human Synergy for Maximum Efficiency",
        ],
        conclusion: "Customer support that feels personal—anytime, anywhere.",
        icon: "🌐",
        color: "blue",
      },
      {
        title: "Why Choose Connektixx for Digital Marketing?",
        tagline: "Data-Driven. Creative. Growth-Focused.",
        features: [
          "Performance Marketing Across Google, Meta & More",
          "Scroll-Stopping Creatives, Conversion-Optimized Copy",
          "End-to-End Funnel Strategy & Execution",
          "Real-Time Analytics, Reporting & Optimization",
          "SEO, Paid Ads, Content & CRM—All Aligned",
          "AI-Led Targeting to Reach the Right Audience",
        ],
        conclusion: "Where creativity meets performance—consistently.",
        icon: "📈",
        color: "purple",
      },
      {
        title: "Why Choose Connektixx for Marketing Consultancy?",
        tagline: "Insightful. Strategic. Impact-Oriented.",
        features: [
          "Tailored Brand Positioning & Market Entry Plans",
          "Cross-Channel Campaign Planning & Execution",
          "GTM Strategy with Competitive Intelligence",
          "Business-Driven Marketing Roadmaps",
          "Offline + Digital Integration for Brand Cohesion",
          "Advisory Backed by Data, Creativity & Industry Know-How",
        ],
        conclusion: "Strategy that moves with your business goals.",
        icon: "💡",
        color: "green",
      },
    ],
  },
  clients: {
    heading: "Our Clients",
    subheading: "We've helped over 511+ brands across various industries optimize their ad performance and boost profitability.",
    cta: "View More Success Stories",
    list: [
      { name: "Client 1", logo: "🏢" },
      { name: "Client 2", logo: "🏢" },
      { name: "Client 3", logo: "🏢" },
      { name: "Client 4", logo: "🏢" },
      { name: "Client 5", logo: "🏢" },
      { name: "Client 6", logo: "🏢" },
      { name: "Client 7", logo: "🏢" },
      { name: "Client 8", logo: "🏢" },
    ],
  },
  reviews: {
    heading: "Client Reviews",
    subheading: "Don't just take our word for it - see what our clients have to say about working with Connektixx",
    cta: "View All Reviews",
    list: [
      { id: 1, name: "Sarah Johnson", initial: "S", company: "E-commerce Store", rating: 5, text: "Connektixx completely transformed our ad strategy. Within just 3 months, our CPA decreased by 42% while our overall sales doubled. Their team is responsive and truly understands what drives results." },
      { id: 2, name: "Michael Chen", initial: "M", company: "SaaS Platform", rating: 5, text: "We've worked with several agencies before, but none delivered like Connektixx. Their data-driven approach and strategic insights have helped us scale our customer acquisition efforts while maintaining profitability." },
      { id: 3, name: "Priya Sharma", initial: "P", company: "D2C Brand", rating: 5, text: "The expertise at Connektixx is unmatched. They took the time to understand our unique business challenges and created a customized strategy that has consistently outperformed our expectations." },
    ],
  },
  faq: {
    heading: "Need Help?",
    headingEmoji: "👨‍💻",
    subheading: "Explore the answers to what makes Connektixx the smart choice for your business.",
    items: [
      { id: 1, question: "What services does Connektixx offer?", answer: "We specialize in Marketing Consultancy, Digital Marketing, and BPO/Call Centre Services—all under one strategic umbrella. Whether you're looking to elevate your brand, boost customer engagement, or streamline backend operations, we deliver AI-enabled solutions that scale with your growth." },
      { id: 2, question: "How is Connektixx different from other agencies or BPO providers?", answer: "We blend human empathy with machine intelligence. Our hybrid model offers high-performance digital marketing and seamless customer support, backed by real-time analytics, automation, and dedicated experts. We're not just vendors—we're growth partners." },
      { id: 3, question: "Can I customize the services based on my business needs?", answer: "Absolutely. At Connektixx, customization is our core strength. We tailor our workflows, communication strategies, and reporting to suit your unique business goals. No cookie-cutter plans—just results that matter." },
      { id: 4, question: "Do you work with startups or only established businesses?", answer: "We work with ambitious startups, scaling businesses, and large enterprises alike. If you're serious about growth, we're serious about helping you get there—fast." },
      { id: 5, question: "What technologies or tools do you use?", answer: "Our stack includes AI-driven CRMs, automation tools, predictive analytics platforms, and leading ad tech. From smart workflows to insightful dashboards, we equip your brand with future-ready solutions." },
      { id: 6, question: "How quickly can I get started?", answer: "In most cases, you can be up and running with us in 7–10 working days. From onboarding to execution, our streamlined setup process ensures you experience impact, not delays." },
      { id: 7, question: "Is multilingual or regional support available in your call centre services?", answer: "Yes! We offer multilingual capabilities and regional adaptability to ensure your customers feel heard—wherever they are. This makes us ideal for businesses with diverse audiences." },
      { id: 8, question: "How do you ensure quality and performance?", answer: "We have strict SLAs, performance dashboards, and continuous agent training in place. Our culture is built around excellence, and our results reflect it." },
      { id: 9, question: "What industries do you serve?", answer: "From agriculture to e-commerce, edtech to fintech, and everything in between—we bring our cross-industry experience to create sharper strategies and richer experiences for your customers." },
      { id: 10, question: "How can I get in touch or request a consultation?", answer: "Just drop us a message, book a discovery call, or send us a WhatsApp ping—we're always ready to Connekt. Your growth story begins with a hello." },
    ],
  },
  contact: {
    pill: "Let's Connect",
    heading: "Get in Touch",
    intro: "Ready to grow, scale, or transform? Whether you're looking to outsource customer support, launch a digital campaign, or craft a full-scale marketing strategy, we'd love to hear from you.",
    formHeading: "Send Us a Message",
    submitBtn: "Submit Inquiry",
    infoHeading: "Contact Information",
    phone: "+91 9220559644",
    email: "pragya.shukla@connektixx.com",
    address: "Your Physical Address or Virtual Location",
    hours: "Monday to Friday, 9 AM – 6 PM",
    consultHeading: "Ready for a Conversation?",
    consultCta: "Schedule a Free Consultation",
    facebook: "https://www.facebook.com/profile.php?id=61576082193640",
    twitter: "#",
    instagram: "#",
    whatsapp: "https://wa.me/919220559644",
    linkedin: "#",
  },
  footer: {
    brandName: "CONNEKTIXX",
    copyright: "© 2025 Connektixx Private Limited |",
    privacyLabel: "Privacy Policy",
    privacyUrl: "#",
    linkedin: "#",
    instagram: "#",
    twitter: "#",
  },
};
