export const defaultContent = {
  navbar: {
    brandName: "CONNEKTIXX",
    navItems: ["Solutions", "How We Partner", "About", "FAQ"],
    cta: "Discuss Your Business Challenge",
  },
  home: {
    eyebrow: "Connektixx Strategic Solutions",
    headline: "Growth strategy, built with you — not sold to you.",
    subtext: "Connektixx is the strategic partner behind the scenes for organisations that want research, customer engagement and growth marketing working as one system — powered by AI, run by people who stay accountable for the outcome.",
    cta: "Discuss Your Business Challenge",
    ctaSecondary: "See Our Solutions",
    chips: ["One partner, full stack", "AI-led, human-verified", "Scoped to fit your size"],
  },
  capabilities: {
    pill: "What We Bring",
    heading: "Built for complex, real-world business challenges",
    subheading: "No fabricated numbers, no borrowed logos — here is what actually stands behind every engagement.",
    items: [
      { title: "One integrated team", description: "Research, customer engagement and growth marketing run by a single accountable team — not handed off between separate vendors." },
      { title: "AI built in, not bolted on", description: "AI is used to structure research, support conversations and reporting from day one — not added later as a feature." },
      { title: "Human oversight on every output", description: "A trained person reviews and owns every AI-assisted deliverable before it reaches you or your customers." },
      { title: "Engagements that scale with you", description: "The same partnership model works as a small, single-service pilot or a full, always-on retainer." },
      { title: "Pan-India, remote-first delivery", description: "A distributed delivery model built to work with organisations wherever their teams and customers are." },
      { title: "Evidence before opinions", description: "Every recommendation is grounded in research and data gathered for your specific business — never a recycled template." },
    ],
    engagementAreas: [
      "Consumer & category research programmes",
      "Customer support & engagement operations",
      "Performance marketing & demand generation",
      "CRM & lifecycle automation",
      "Brand positioning & go-to-market planning",
      "Workflow & reporting automation",
    ],
  },
  solutions: {
    pill: "Solutions",
    heading: "Four capability areas. One accountable partner.",
    subheading: "Most organisations stitch together a research vendor, a support desk and a marketing agency separately — and pay for the handoffs between them. Connektixx runs all four capability areas as one team.",
    pillars: [
      {
        tag: "01 · Market Intelligence & Business Insights",
        promise: "Decisions built on evidence, not guesswork",
        description: "Structured research and market understanding that leadership can act on immediately.",
        offerings: [
          { title: "AI-Led Market Research", description: "Full studies designed, fielded and analysed end-to-end — AI structures every conversation into decision-ready insight, not raw transcripts." },
          { title: "Brand & Market Positioning", description: "A clear, defensible position in your category — the story every campaign and pitch ladders back to." },
          { title: "Data & Reporting Dashboards", description: "Manual reporting replaced with live dashboards built around the metrics that actually drive your decisions." },
        ],
      },
      {
        tag: "02 · Customer Experience & Engagement",
        promise: "Every conversation handled like it matters",
        description: "Support, engagement and relationship management run as one consistent customer experience.",
        offerings: [
          { title: "Customer Support, Inbound & Outbound", description: "Support, lead qualification and retention calling handled as one experience — AI-assisted first response, with a trained human behind every escalation." },
          { title: "Conversational AI & Chat Assistance", description: "AI-guided chat support that answers instantly and hands off to a person the moment a query needs judgement." },
          { title: "CRM & Lifecycle Engagement", description: "Every customer relationship nurtured on autopilot, personalised by AI, without ever feeling automated." },
        ],
      },
      {
        tag: "03 · Digital Growth & Demand Generation",
        promise: "A growth engine, not a list of tactics",
        description: "Owned, earned and paid channels designed and run as one system — never in silos.",
        offerings: [
          { title: "Performance & Organic Growth", description: "Paid media and search visibility managed as one acquisition engine, optimised against paying customers — not vanity clicks." },
          { title: "Content, Creative & Brand Systems", description: "Research-backed content and creative produced at the pace AI enables, without losing a consistent brand voice." },
          { title: "Go-To-Market & Campaign Rollouts", description: "Launch and growth plans mapped as one phased rollout, built on real market intelligence, not a recycled playbook." },
        ],
      },
      {
        tag: "04 · AI Automation & Business Transformation",
        promise: "Where repeatable work becomes a managed system",
        description: "The operational layer that turns manual, repeatable work into AI-assisted, human-supervised process.",
        offerings: [
          { title: "Process & Workflow Automation", description: "Back-office work and manual reporting replaced with AI-driven workflows — decisions in hours, not weeks." },
          { title: "Data Integration & Systems Modernisation", description: "Disconnected spreadsheets and tools brought into one coherent, current view of your business." },
          { title: "AI Readiness & Transformation Advisory", description: "A practical, sequenced plan for where AI genuinely helps your business — and where it doesn't, yet." },
        ],
      },
    ],
  },
  howWePartner: {
    pill: "How We Partner",
    heading: "A partner in your corner — not a vendor at arm's length",
    subheading: '"Agency" implies a brief goes out and a deliverable comes back. That\'s not how an integrated strategic partnership works.',
    philosophy: [
      { title: "Partner, not vendor", description: "We sit inside your growth strategy and answer for the outcome — not a vendor waiting on the next brief." },
      { title: "One team, full stack", description: "Research, engagement and growth marketing under one roof, so nothing gets lost between separate vendors." },
      { title: "AI + human, by design", description: "Every AI-led offering keeps a trained person in the loop — speed without losing judgement." },
      { title: "Built to scale with you", description: "The same partnership model whether you're an early-stage brand or an established enterprise — scope grows with you, not ahead of you." },
    ],
    ladderIntro: "Start small. Prove value. Scale with confidence.",
    ladderSub: "Every partnership begins the same low-risk way — a focused pilot, not a long contract.",
    ladder: [
      { step: "STEP 1", title: "Pilot", description: "A focused, time-boxed engagement on one offering — one research study, one campaign, one desk — for fast, low-risk proof of value." },
      { step: "STEP 2", title: "Scale", description: "Expand the proven offering across teams, regions or channels, with scope and pricing aligned to the results you've already seen." },
      { step: "STEP 3", title: "Partner", description: "A retained, always-on strategic partnership spanning research, engagement and growth — your extended growth team.", highlight: true },
    ],
  },
  about: {
    pill: "About Connektixx",
    heading: "Why we exist",
    lead: "We started Connektixx because research, customer engagement and growth marketing kept being sold as three separate purchases — when in every business we'd worked with, they were really one conversation with the customer, cut into pieces by three different vendors.",
    principles: [
      { title: "Integrated by default", description: "We don't sell services in isolation. Research findings inform the next campaign; support conversations inform the CRM; every capability feeds the others." },
      { title: "Strategic partner, not an agency", description: "We work as an embedded extension of your team, accountable for outcomes — not a vendor waiting on a brief." },
      { title: "AI accelerates; people decide", description: "AI handles volume and speed. A trained person reviews, decides and owns every client-facing outcome." },
      { title: "Right-sized, not one-size-fits-all", description: "The same partnership model is scoped differently for a five-person startup and an established enterprise." },
      { title: "Measurable and transparent", description: "Every engagement starts with clearly agreed metrics, and we report against them — not around them." },
    ],
  },
  faq: {
    pill: "Questions",
    heading: "Good to know before we talk",
    items: [
      { id: 1, question: "What makes Connektixx different from a typical agency or BPO?", answer: "We don't hand you off between three vendors. One team runs your research, customer engagement and growth marketing together, with AI built into how we work rather than sold as an add-on." },
      { id: 2, question: "Do you only work with large organisations?", answer: "No. The partnership model scales down as easily as it scales up. We work with early-stage brands the same way we work with established enterprises — just scoped differently." },
      { id: 3, question: 'What does "AI-led" actually mean in your services?', answer: "AI handles the volume — structuring conversations, drafting content, running first-response support — while a trained person reviews, decides and owns every outcome. AI never runs unattended on anything client-facing." },
      { id: 4, question: "Can we start with just one capability area, like market research?", answer: "Yes. Most partnerships start with a single, focused engagement and expand once we've proven the model together." },
      { id: 5, question: "Do you work with organisations outside India?", answer: "Our team and delivery are based in India, and we work with organisations across geographies — the same model applies wherever your customers are." },
      { id: 6, question: "How is pricing structured?", answer: "Every engagement starts as a conversation about scope, not a fixed rate card. Most partnerships begin with a focused pilot before scaling into a retainer." },
      { id: 7, question: "What sectors do you work in?", answer: "We work across a range of industries and take on new categories on a case-by-case basis — if you're unsure whether we're a fit, ask us directly." },
      { id: 8, question: "How quickly can we get started?", answer: "A first conversation and a scoped pilot plan typically take one to two weeks. We deliberately start small so both sides can see the model work before committing further." },
    ],
  },
  contact: {
    pill: "Get In Touch",
    heading: "Tell us what you're trying to solve.",
    intro: "Share a bit about your business challenge — we'll come back with a clear, scoped way to start.",
    submitBtn: "Discuss Your Business Challenge",
    infoHeading: "Contact Information",
    email: "support@connektixx.com",
    whereWeWork: "Pan-India · remote-first delivery",
    hours: "Mon – Fri, 9 AM – 6 PM IST",
    linkedin: "https://www.linkedin.com/company/109331917/",
    dropdownOptions: [
      "Market Intelligence & Business Insights",
      "Customer Experience & Engagement",
      "Digital Growth & Demand Generation",
      "AI Automation & Business Transformation",
      "Not sure yet — general enquiry",
      "Other",
    ],
  },
  footer: {
    brandName: "CONNEKTIXX",
    tagline: "An integrated strategic partner for research, customer engagement and growth marketing — built on AI, run by people who stay accountable for the outcome.",
    closing: "Let's Connekt.",
    copyright: `© ${new Date().getFullYear()} Connektixx Strategic Solutions. All rights reserved.`,
    siteLinks: [
      { label: "Solutions", href: "#solutions" },
      { label: "How We Partner", href: "#how-we-partner" },
      { label: "About", href: "#about" },
      { label: "FAQ", href: "#faq" },
      { label: "Contact", href: "#contact" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Use", href: "#" },
      { label: "Cookie Policy", href: "#" },
    ],
    email: "support@connektixx.com",
    linkedin: "https://www.linkedin.com/company/109331917/",
  },
};
